export const cssQuizDetails = {
  FreeQuiz: {
    description: "A Beginner's Guide to CSS Fundamentals",
    key: "free",
    topics: [
      {
        quizName: "Basic CSS Assessment",
        id: "quizCSSFree1",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: true,
        duration: "15 minutes",
      },
    ],
    totalTopics: 1,
    completedTopics: 0,
    subscribed: true,
  },

  Beginner: {
    description: "Grasp Essential CSS Concepts",
    key: "beginner",
    topics: [
      {
        quizName: "CSS Syntax and Selectors",
        description: "Learn the basics of CSS syntax and various selectors.",
        id: "quizCSSBeginner1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Box Model and Box Sizing",
        description:
          "Dive into margin, border, padding, and content management.",
        id: "quizCSSBeginner2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Text Styling and Colors",
        description:
          "Explore font properties, text alignment, and color formats.",
        id: "quizCSSBeginner3",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "25 minutes",
      },
      {
        quizName: "Backgrounds and Display",
        description: "Understand background properties and display types.",
        id: "quizCSSBeginner4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
    ],
    totalTopics: 4,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Intermediate: {
    description: "Enhance Your CSS Proficiency",
    key: "intermediate",
    topics: [
      {
        quizName: "Positioning",
        description:
          "Master static, relative, absolute, fixed, and sticky positioning.",
        id: "quizCSSIntermediate1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Flexbox Layout",
        description: "Learn key Flexbox properties for efficient layouts.",
        id: "quizCSSIntermediate2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "CSS Grid Layout",
        description: "Understand CSS Grid basics for advanced layouts.",
        id: "quizCSSIntermediate3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "CSS Transitions and Animations",
        description:
          "Explore keyframes, transitions, and animation properties.",
        id: "quizCSSIntermediate4",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "30 minutes",
      },
    ],
    totalTopics: 4,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Advanced: {
    description: "Achieve Mastery in CSS",
    key: "advanced",
    topics: [
      {
        quizName: "CSS Variables (Custom Properties)",
        description: "Learn about CSS variables, their scope, and fallbacks.",
        id: "quizCSSAdvanced1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Responsive Design",
        description:
          "Implement media queries and use responsive units effectively.",
        id: "quizCSSAdvanced2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Tailwind CSS",
        description:
          "Understand the utility-first CSS framework, Tailwind CSS.",
        id: "quizCSSAdvanced3",
        totalQuestions: 20,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "40 minutes",
      },
      {
        quizName: "Full CSS Assessment",
        description: "Comprehensive review of all CSS concepts and techniques.",
        id: "quizCSSAdvanced4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "30 minutes",
      },
    ],
    totalTopics: 4,
    completedTopics: 0,
    cost: 100,
    subscribed: false,
  },
};
