export const javaScriptQuizDetails = {
  FreeQuiz: {
    description: "Introduction to JavaScript Fundamentals",
    key: "free",
    topics: [
      {
        quizName: "JavaScript Basics Assessment",
        description:
          "An introductory quiz covering fundamental JavaScript concepts.",
        id: "quizJSFree1",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: true,
        duration: "15 minutes",
      },
    ],
    totalTopics: 1,
    completedTopics: 0,
    subscribed: true,
  },

  Beginner: {
    description: "Master Fundamental JavaScript Concepts",
    key: "beginner",
    topics: [
      {
        quizName: "Variables and Data Types",
        description:
          "Understanding variables, data types, and scope in JavaScript.",
        id: "quizJSBeginner1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "15 minutes",
      },
      {
        quizName: "Operators and Expressions",
        description:
          "Learn about different operators and how to use them in expressions.",
        id: "quizJSBeginner2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "15 minutes",
      },
      {
        quizName: "Functions and Scope",
        description:
          "Dive into function declarations, expressions, and scope management.",
        id: "quizJSBeginner3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Control Structures",
        description:
          "Explore control structures like loops, if-else, and switch statements.",
        id: "quizJSBeginner4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Arrays and Objects",
        description:
          "Learn how to work with arrays and objects, and their methods.",
        id: "quizJSBeginner5",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
    ],
    totalTopics: 5,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Intermediate: {
    description: "Enhance Your JavaScript Skills",
    key: "intermediate",
    topics: [
      {
        quizName: "ES6 Features",
        description:
          "Understanding new features introduced in ES6, like let, const, and arrow functions.",
        id: "quizJSIntermediate1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Promises and Async/Await",
        description:
          "Learn how to handle asynchronous operations using Promises and async/await.",
        id: "quizJSIntermediate2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "DOM Manipulation",
        description: "Explore how to manipulate the DOM using JavaScript.",
        id: "quizJSIntermediate3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Event Handling",
        description:
          "Learn about event propagation, capturing, and handling events.",
        id: "quizJSIntermediate4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Closures and Callbacks",
        description:
          "Understand closures, callbacks, and their applications in JavaScript.",
        id: "quizJSIntermediate5",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
    ],
    totalTopics: 5,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Advanced: {
    description: "Master Advanced JavaScript Techniques",
    key: "advanced",
    topics: [
      {
        quizName: "Object-Oriented Programming (OOP)",
        description:
          "Explore OOP principles in JavaScript, including classes and inheritance.",
        id: "quizJSAdvanced1",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "25 minutes",
      },
      {
        quizName: "Functional Programming",
        description:
          "Learn about functional programming concepts like higher-order functions and immutability.",
        id: "quizJSAdvanced2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Error Handling and Debugging",
        description:
          "Understand error handling techniques and debugging strategies.",
        id: "quizJSAdvanced3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Modules and Tooling",
        description:
          "Explore JavaScript modules, bundlers, and modern tooling like Webpack and Babel.",
        id: "quizJSAdvanced4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Performance Optimization",
        description: "Learn techniques to optimize JavaScript performance.",
        id: "quizJSAdvanced5",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Security Best Practices",
        description:
          "Understand common security vulnerabilities and how to mitigate them in JavaScript.",
        id: "quizJSAdvanced6",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Web APIs",
        description:
          "Explore various Web APIs and how to use them effectively.",
        id: "quizJSAdvanced7",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Testing and TDD",
        description:
          "Learn about testing methodologies and Test-Driven Development (TDD) in JavaScript.",
        id: "quizJSAdvanced8",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Advanced JavaScript Assessment",
        description:
          "A comprehensive quiz covering advanced JavaScript concepts.",
        id: "quizJSAdvanced9",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "30 minutes",
      },
    ],
    totalTopics: 9,
    completedTopics: 0,
    cost: 100,
    subscribed: false,
  },
};
