export const reactQuizDetails = {
  FreeQuiz: {
    description: "Introduction to React Fundamentals",
    key: "free",
    topics: [
      {
        quizName: "React Basics Assessment",
        description:
          "An introductory quiz covering fundamental React concepts.",
        id: "quizReactFree1",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: true,
        duration: "15 minutes",
      },
    ],
    totalTopics: 1,
    completedTopics: 0,
    subscribed: true,
  },

  Beginner: {
    description: "Master the Essentials of React",
    key: "beginner",
    topics: [
      {
        quizName: "JSX and Rendering",
        description:
          "Understanding JSX syntax and rendering elements in React.",
        id: "quizReactBeginner1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Components and Props",
        description:
          "Learn about functional and class components, and passing props.",
        id: "quizReactBeginner2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "State and Lifecycle",
        description:
          "Explore state management and component lifecycle methods.",
        id: "quizReactBeginner3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Handling Events",
        description: "Learn how to handle user events in React applications.",
        id: "quizReactBeginner4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "15 minutes",
      },
    ],
    totalTopics: 4,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Intermediate: {
    description: "Enhance Your React Skills",
    key: "intermediate",
    topics: [
      {
        quizName: "React Hooks Overview",
        description: "Understanding React Hooks like useState and useEffect.",
        id: "quizReactIntermediate1",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Context API",
        description: "Learn how to manage global state using the Context API.",
        id: "quizReactIntermediate2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "React Router",
        description: "Explore client-side routing using React Router.",
        id: "quizReactIntermediate3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Form Handling",
        description: "Learn how to handle forms and form validation in React.",
        id: "quizReactIntermediate4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "15 minutes",
      },
    ],
    totalTopics: 4,
    completedTopics: 0,
    cost: 100,
    subscribed: true,
  },

  Advanced: {
    description: "Master Advanced React Techniques",
    key: "advanced",
    topics: [
      {
        quizName: "Redux for State Management",
        description:
          "Dive into Redux for managing complex state in React apps.",
        id: "quizReactAdvanced1",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "25 minutes",
      },
      {
        quizName: "Server-Side Rendering (SSR)",
        description:
          "Understand the concepts and implementation of SSR in React.",
        id: "quizReactAdvanced2",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Performance Optimization",
        description: "Learn techniques to optimize performance in React apps.",
        id: "quizReactAdvanced3",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Testing in React",
        description:
          "Explore testing strategies and tools for React applications.",
        id: "quizReactAdvanced4",
        totalQuestions: 10,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "20 minutes",
      },
      {
        quizName: "Full React Assessment",
        description:
          "A comprehensive quiz covering all aspects of React, from basics to advanced topics.",
        id: "quizReactAdvanced5",
        totalQuestions: 15,
        completedQuestions: 0,
        isCompleted: false,
        progress: 0,
        active: false,
        duration: "30 minutes",
      },
    ],
    totalTopics: 5,
    completedTopics: 0,
    cost: 100,
    subscribed: false,
  },
};
